name: CI

on: [push]

jobs:

  python-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Get changes python files
      id: files
      run: |
        echo "::set-output name=all::$(echo $(git ls-tree --full-tree -r --name-only HEAD | grep \.py$))"
        echo "::set-output name=changed::$(echo $(git diff --name-only ${{ github.sha }} | grep \.py$))"

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      if: steps.files.outputs.all

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
        pip install pydocstyle
      if: steps.files.outputs.all

    - name: Analyse the code with pycodestyle
      run: pycodestyle ${{steps.files.outputs.all}}
      if: steps.files.outputs.all

    - name: Analyse the documentation with pydocstyle
      run: pydocstyle --ignore=D105,D407,D212,D203 ${{steps.files.outputs.all}}
      if: steps.files.outputs.all


  dockerfile-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Get changed Dockerfiles
      id: files
      run: |
        echo "::set-output name=all::$(echo $(git ls-tree --full-tree -r --name-only HEAD | grep Dockerfile))"
        echo "::set-output name=changed::$(echo $(git diff --name-only ${{ github.sha }} | grep Dockerfile))"

    - name: Set up NPM
      uses: actions/setup-node@v1
      with:
        node-version: '12'
      if: steps.files.outputs.all

    - name: Installing dependencies
      run: npm install -g dockerfilelint
      if: steps.files.outputs.all

    - name: Analyse DockerFiles
      run: dockerfilelint ${{ steps.files.outputs.all }}
      if: steps.files.outputs.all

  shell-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Get changed shell script
      id: files
      run: |
        echo "::set-output name=all::$(echo $(git ls-tree --full-tree -r --name-only HEAD | grep \.sh$))"
        echo "::set-output name=changed::$(echo $(git diff --name-only ${{ github.sha }} | grep \.sh$))"

    - name: Installing dependencies
      run: sudo apt install -y shellcheck
      if: steps.files.outputs.all

    - name: Analyse shell scripts
      run: shellcheck ${{ steps.files.outputs.all }}
      if: steps.files.outputs.all

  test:
    runs-on: ubuntu-latest
    needs: [python-lint, dockerfile-lint, shell-lint]

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Build environment
      run: docker build -t nopandas .

    - name: Run tests
      run: docker run nopandas test
